version: 0.0
os: linux
files:
  - source: stop.sh
    destination: /var/tmp
hooks:
  BeforeInstall:
    - location: stop.sh
  AfterInstall:
    - location: stop.sh
  ApplicationStart:
    - location: start.sh
  ValidateService:
    - location: start.sh
      timeout: 3600
