version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
  parameter-store:
    LOGIN_PASSWORD: /CodeBuild/dockerLoginPassword

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - printenv
      - echo "password is $LOGIN_PASSWORD"
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
artifacts:
  files:
    - "**/*"
  discard-paths: yes
  secondary-artifacts:
    artifact1:
      files:
        - "**/*.sh"
      discard-paths: yes
    artifact2:
      files:
        - "**/*.yml"
      discard-paths: yes
